<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="QA-Imran" ignored="0" name="Command line test" tests="14" failures="3" timestamp="03 Aug 2018 08:31:15 GMT" time="52.84" errors="0">
  <testcase name="loginPortal" time="6.489" classname="com.icreon.account.firstLoginTest"/>
  <testcase name="TC_001_Passing0InPath" time="2.548" classname="com.icreon.customer.customerProfileInformationTest"/>
  <testcase name="TC_002_PassingProfileIDinPath" time="0.517" classname="com.icreon.customer.customerProfileInformationTest">
    <failure type="java.lang.AssertionError" message="expected [404] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [404] but found [200]
at com.icreon.customer.customerProfileInformationTest.TC_002_PassingProfileIDinPath(customerProfileInformationTest.java:91)
... Removed 41 stack frames]]>
    </failure>
  </testcase> <!-- TC_002_PassingProfileIDinPath -->
  <testcase name="TC_003_PassingWrongProfileIDinPath" time="0.581" classname="com.icreon.customer.customerProfileInformationTest"/>
  <testcase name="TC_004_requestWithoutAuthorization" time="0.963" classname="com.icreon.customer.customerProfileInformationTest"/>
  <testcase name="TC_005_requestWithoutX_Fred_Auth" time="0.571" classname="com.icreon.customer.customerProfileInformationTest"/>
  <testcase name="TC_006_requestWithoutCustomerId" time="0.484" classname="com.icreon.customer.customerProfileInformationTest"/>
  <testcase name="TC_007_mismatchedCustomerId" time="0.487" classname="com.icreon.customer.customerProfileInformationTest"/>
  <testcase name="custProfileInfo" time="0.734" classname="com.icreon.customer.customerProfileInformationTest"/>
  <testcase name="TC_001_SavingANewKid" time="1.337" classname="com.icreon.customer.kidTest"/>
  <testcase name="TC_001_MileageNumberAlreadyExist" time="31.137" classname="com.icreon.customer.MileagePlusRewardNumberTest">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Expected status code &amp;lt;200&amp;gt; but was &amp;lt;404&amp;gt;.
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <404>.

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:483)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:655)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:123)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:131)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:119)
at com.icreon.customer.MileagePlusRewardNumberTest.TC_001_MileageNumberAlreadyExist(MileagePlusRewardNumberTest.java:36)
... Removed 45 stack frames]]>
    </failure>
  </testcase> <!-- TC_001_MileageNumberAlreadyExist -->
  <testcase name="TC_002_MileageNumberNotValid" time="0.573" classname="com.icreon.customer.MileagePlusRewardNumberTest"/>
  <testcase name="TC_001_PassingAllParametersCorrectly" time="2.008" classname="com.icreon.customer.stravaUpdateTest"/>
  <testcase name="TC_002_UsingExsitingStravaId" time="4.01" classname="com.icreon.customer.stravaUpdateTest">
    <failure type="java.lang.AssertionError" message="expected [Success] but found [Starva Id already exist]">
      <![CDATA[java.lang.AssertionError: expected [Success] but found [Starva Id already exist]
at com.icreon.customer.stravaUpdateTest.TC_002_UsingExsitingStravaId(stravaUpdateTest.java:80)
... Removed 41 stack frames]]>
    </failure>
  </testcase> <!-- TC_002_UsingExsitingStravaId -->
</testsuite> <!-- Command line test -->
